### PR TITLE
Database performance

### PR DESCRIPTION
**Pull request by imubarak234**
The following queries are taking too much time (1 sec = 1000ms can be considered as too much time for database query). Try them on your machine to confirm it:

SELECT COUNT(*) FROM visits where animal_id = 4;
SELECT * FROM visits where vet_id = 2;
SELECT * FROM owners where email = 'owner_18327@mail.com';
Use EXPLAIN ANALYZE on the previous queries to check what is happening. Take screenshots of them - they will be necessary later.

Find a way to decrease the execution time of the first query. Look for hints in the previous lessons.

Find a way to improve the execution time of the other two queries.

While you are making changes, check if they help by running EXPLAIN ANALYZE. Once you succeed, take a screenshot of the EXPLAIN ANALYZE result showing that time actually decreased.

Any changes you made to your database schema should be added to the schema.sql file and committed in a new pull request.

If you decide to commit any INSERT INTO queries - remember to add them to the data.sql file. It is important to keep only the queries that change the database structure in the schema.sql file.

In your pull request description include screenshots with EXPLAIN ANALYZE results (before and after you improve the speed) for each of the 3 problematic queries.

##Screenshots
- SELECT COUNT(*) FROM visits where animal_id = 4;
##Before
First Problem
##After
First Solution

- SELECT * FROM visits where vet_id = 2;
##Before
Second Problem01

##After
Second Solution01

-SELECT * FROM owners where email = 'owner_18327@mail.com';
##Before 
Third Problem
##After
Third Solution

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
Hi @imubarak234, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] There was no improvement for your second query which was `SELECT * FROM visits where vet_id = 2;`. the first screenshot is showing that the execution time was `2752.733ms` and the second screenshot is showing that the execution time increased. `2803.419ms`. which should not be the case since you were supposed to be improving the query. Kindly fix it. One of the simplest solutions for performance is adding indexes. go to your scheme file and add the following lines: 
  
```sql 
   CREATE INDEX ON visits (animal_id);
   CREATE INDEX ON visits (vet_id);
   CREATE INDEX ON owners (email);
```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by imubarak234** [comment]
> Hi @imubarak234,
> 
> _Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
> 
> ## Highlights
> * Follows git workflow.  💯
> * Codebase looks clean and professional. 💯
> 
> ## Required Changes ♻️
> * [ ]  There was no improvement for your second query which was `SELECT * FROM visits where vet_id = 2;`. the first screenshot is showing that the execution time was `2752.733ms` and the second screenshot is showing that the execution time increased. `2803.419ms`. which should not be the case since you were supposed to be improving the query. Kindly fix it. One of the simplest solutions for performance is adding indexes. go to your scheme file and add the following lines:
> 
> ```sql
>    CREATE INDEX ON visits (animal_id);
>    CREATE INDEX ON visits (vet_id);
>    CREATE INDEX ON owners (email);
> ```
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * [ ]  Check the comments under the review.
> 
> Cheers and Happy coding!👏👏👏
> 
> **Feel free to leave any questions or comments in the PR thread if something is not 100% clear.**
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> > As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by imubarak234** [comment]
I mixed up the screenshots, I've uploaded the right ones

**Review by addod19 — APPROVED** [review]
### Hi @imubarak234, 

Your project is complete! Nice work correcting the mix up screenshot :fireworks:  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
